- name: "pacman -Syu as a separate step"
  pacman:
    update_cache: yes
    upgrade: yes

- name: install hyprland packages 
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ lookup('file', 'files/packages.txt').splitlines() }}"

- name: copy hyprland config
  copy:
    src: files/hyprland.conf
    dest: "/home/{{ home_user }}/.config/hypr/hyprland.conf"
    owner: "{{ home_user }}"
    group: "{{ home_user }}"

- name: copy vol.sh
  copy:
    src: files/vol.sh
    dest: "/home/{{ home_user }}/config/hypr/sh/vol.sh"
    owner: "{{ home_user }}"   
    group: "{{ home_user }}"

- name: copy toogle_waybar
  copy:
    src: files/toogle_waybar.sh
    dest: "/home/{{ home_user }}/.config/hypr/sh/toogle_waybar.sh"
    owner: "{{ home_user }}"   
    group: "{{ home_user }}"   

- name: copy set wallpaper
  copy:
    src: files/set-wallpaper.sh
    dest: "/home/{{ home_user }}/.config/hypr/sh/set-wallpaper.sh"
    owner: "{{ home_user }}"   
    group: "{{ home_user }}"   

- name: copy wallpapers
  copy:
    src: files/backgrounds/*
    dest: "/home/{{ home_user }}/.config/backgrounds/"
    owner: "{{ home_user }}"   
    group: "{{ home_user }}"   

