- name: "pacman -Syu as a separate step"
  pacman:
    update_cache: yes
    upgrade: yes

- name: install hyprland packages 
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ lookup('file', 'files/packages.txt').splitlines() }}"

- name: copy hyprland config
  copy:
    src: files/hyprland.conf
    dest: "/home/andreas/.config/hypr/hyprland.conf"
    owner: andreas
    group: andreas
    backup: yes

- name: copy vol.sh
  copy:
    src: files/vol.sh
    dest: "/home/andreas/config/hypr/sh/vol.sh"
    owner: andreas   
    group: andreas

- name: copy toogle_waybar
  copy:
    src: files/toogle_waybar.sh
    dest: "/home/andreas/.config/hypr/sh/toogle_waybar.sh"
    owner: andreas   
    group: andreas   

- name: copy set wallpaper
  copy:
    src: files/set-wallpaper.sh
    dest: "/home/andreas/.config/hypr/sh/set-wallpaper.sh"
    owner: andreas   
    group: andreas   

- name: copy wallpapers
  copy:
    src: files/backgrounds/*
    dest: "/home/andreas/.config/backgrounds/"
    owner: andreas   
    group: andreas   

