- name: "pacman -Syu as a separate step"
  pacman:
    update_cache: yes
    upgrade: yes

- name: install hyprland packages 
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ lookup('file', 'files/packages.txt').splitlines() }}"

- name: copy hyprland config
  copy:
    src: files/hyprland.conf
    dest: "{{ config_path }}/hypr/hyprland.conf"
    owner: andreas
    group: andreas
    backup: yes

- name: copy vol.sh
  copy:
    src: files/vol.sh
    dest: "{{ config_path }}/hypr/sh/"
    owner: andreas   
    group: andreas

- name: copy toggle_waybar
  copy:
    src: files/toggle_waybar.sh
    dest: "{{ config_path }}/hypr/sh/"
    owner: andreas   
    group: andreas   

- name: copy set wallpaper
  copy:
    src: files/set-wallpaper.sh
    dest: "{{ config_path }}/hypr/sh/"
    owner: andreas   
    group: andreas   

- name: copy wallpapers
  copy:
    src: files/backgrounds
    dest: "{{ config_path }}/"
    owner: andreas   
    group: andreas   

- name: configure mako
  copy:
    src: files/config
    dest: "{{ config_path }}/mako/"
    owner: andreas
    group: andreas

- name: Run mako as service
  systemd:
    state: started
    name: mako
    scope: user
    no_block: true

