- name: "pacman -Syu as a separate step"
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

      #- name: install hyprland packages 
      #  become: true
      #  package:
      #    name: "{{ item }}"
      #    state: present
      #  loop: "{{ lookup('file', 'files/packages.txt').splitlines() }}"

- name: install hyprland packages 
  become: true
  package:
    name: "{{ hyprland_packages }}"
    state: present

- name: copy hyprland conf
  copy:
    src: files/hyprland.conf
    dest: "/home/andreas/.config/hypr/hyprland.conf"
    owner: andreas
    group: andreas
    backup: yes

- name: copy vol.sh
  copy:
    src: files/vol.sh
    dest: "/home/andreas/.config/hypr/sh/"
    owner: andreas   
    group: andreas

- name: copy toggle_waybar
  copy:
    src: files/toggle_waybar.sh
    dest: "/home/andreas/.config/hypr/sh/"
    owner: andreas   
    group: andreas   

- name: copy set wallpaper
  copy:
    src: files/set-wallpaper.sh
    dest: "/home/andreas/.config/hypr/sh/"
    owner: andreas   
    group: andreas   

- name: copy wallpapers
  copy:
    src: files/backgrounds
    dest: "/home/andreas/.config/"
    owner: andreas   
    group: andreas   

- name: confure mako
  copy:
    src: files/mako/config
    dest: "/home/andreas/.config/mako/"
    owner: andreas
    group: andreas

- name: Run mako as service
  systemd:
    state: started
    name: mako
    scope: user
    no_block: true

