---
update: true
swapfile_path: /swapfile
swapfile_size: 8G
conf_path: "/home/andreas/.config/"

base_packages:
  - sudo
  - netctl
  - openssh
  - man-db
  - man-pages
  - man-pages-de
  - wget
  - reflector
  - pulseaudio
  - git
  - bash-completion

hyprland_packages:
  - alsa-utils
  - firefox
  - foot
  - greetd
  - greetd-tuigreet
  - grim
  - gtkspell
  - hyprland
  - lxqt-policykit
  - mako
  - pavucontrol
  - swaylock
  - thunar
  - tumbler
  - waybar
  - wl-clipboard
  - wofi
  - xdg-utils
  - zathura-pdf-poppler

font_packages:
  - ttf-ubuntu-font-family
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji # for emoji
  - ttf-dejavu
  - ttf-roboto
  - adobe-source-han-sans-otc-fonts # for CJK
  - ttf-firacode-nerd
  - ttf-jetbrains-mono-nerd
  - ttf-mplus-nerd

aur_packages:
  - nitch
  - swww
  - actkbd

other_packages:
  - ripgrep
  - rsync
  - scdoc
  - slurp
  - starship
  - tree
  - unarchiver
  - yazi
  - zathura
  - zoxide
  - nsxiv
  - w3m
  - mosh
  - ouch
  - hexyl
  - miller
  - poppler
  - blueman
  - brightnessctl
  - fd
  - ffmpegthumbnailer
  - fzf
  - glow
  - gvfs
  - jq
  - mpc
  - mpd
  - mpv
  - neovim
  - chrony
  - compface
  - mpv-mpris
  - aria2
  - yay
  - pass
  - spotify
  - spotify-adblock-git
  - yt-dlp
  - ntfs-3g
  - btop
  - geary
  - browserpass-firefox
  - browserpass-chromium
  - tmux
  - bc
  - p7zip

services_list:
  - sshd
  - NetworkManager
  - reflector

dev_packages:
  - visual-studio-code-bin
