---
- hosts: localhost
  connection: local

  vars_files:
    - default.config.yml
    - config.yml

  roles:
    - aur
    - base
    - shell
    - hyprland
    - foot
    #    - waybar
    #    - greetd
    #    - yazi
    #    - users
