---

- hosts: localhost
  connection: local

  roles:
    #  - users
    #  - write-dotfiles
    #  - terminal-packages
    #  - hyprland
    #  - terminal
    #  - waybar
    #  - greetd
    - yazi

