- name: copy greetd config
  copy:
    src: files/config.toml
    dest: "/home/andreas/.config/greetd/config.toml"
    owner: andreas
    group: andreas
    mode: 0644

- name: Run greetd as service
  systemd:
    state: started
    name: greetd
    enable: true
