- name: copy greetd config
  copy:
    src: files/config.toml
    dest: "{{ conf_path }}greetd/"
    owner: andreas
    group: andreas
    mode: 0644

- name: Run greetd as service
  become: true
  systemd:
    state: started
    name: greetd
    enabled: true
