- name: Install Yazi catppuccin themes
  ansible.builtin.git:
    repo: "https://github.com/catppuccin/yazi.git"
    dest: /home/andreas/.config/yazi/

- name: Copy Yazi.toml
  copy:
    src: files/
    dest: /home/andreas/.config/yazi/

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/andreas/.config/yazi/plugins/smart-enter.yazi
    state: directory
    mode: '0755'

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/andreas/.config/yazi/plugins/arrow.yazi
    state: directory
    mode: '0755'
      
- name: copy Yazi plugin (Smart Enter)
  copy:
    src: templates/smart-enter.yazi/init.lua.j2
    dest: /home/andreas/.config/yazi/plugins/smart-enter.yazi/init.lua
    owner: andreas
    group: andreas

- name: copy Yazi plugin (Arrow)
  copy:
    src: templates/arrow.yazi/init.lua.j2
    dest: /home/andreas/.config/yazi/plugins/arrow.yazi/init.lua
    owner: andreas
    group: andreas

- name: Install Yazi Mime plugin 
  ansible.builtin.git:
    repo: "https://github.com/DreamMaoMao/mime.yazi.git"
    dest: /home/andreas/.config/yazi/plugins/mime.yazi/

- name: Install Yazi Glow plugin (Markdown viewer)
  ansible.builtin.git:
    repo: "https://github.com/NvChad/starter.git"
    dest: /home/andreas/.config/yazi/plugins/glow.yazi/

- name: Install Yazi Miller plugin (CSV viewer)
  ansible.builtin.git:
    repo: "https://github.com/Reledia/miller.yazi.git"
    dest: /home/andreas/.config/yazi/plugins/miller.yazi/

- name: Install Yazi Hexyl plugin (Binary viewer)
  ansible.builtin.git:
    repo: "https://github.com/Reledia/hexyl.yazi.git"
    dest: /home/andreas/.config/yazi/plugins/hexyl.yazi/

- name: Install Yazi Exifaudio plugin (Exif audio viewer)
  ansible.builtin.git:
    repo: "https://github.com/Sonico98/exifaudio.yazi.git"
    dest: /home/andreas/.config/yazi/plugins/exifaudio-yazi/
      
- name: Install Yazi Ouch plugin (Archive viewer)
  ansible.builtin.git:
    repo: "https://github.com/ndtoan96/ouch.yazi.git"
    dest: /home/andreas/.config/yazi/plugins/ouch-yazi/



