- name: Copy waybar config
  copy:
    src: files/config.jsonc
    dest: "/home/andreas/.config/waybar/config.jsonc"
    owner: andreas
    group: andreas
    mode: 0644

- name: Copy waybar style
  copy:
    src: files/style.css
    dest: "/home/andreas/.config/waybar/style.css"
    owner: andreas
    group: andreas
    mode: 0644


