- name: "pacman -Syu as a separate step"
  pacman:
    update_cache: yes
    upgrade: yes

- name: install missing packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ lookup('file', 'files/packages.txt').splitlines() }}"
