- name: Install base packages
  become: true
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  changed_when: false

- name: install font packages
  become: true
  community.general.pacman:
    name: "{{ font_packages }}"
    state: present
  changed_when: false

- import_tasks: tasks/aur-packages.yml
